services:

  postgres:
    image: postgres:16
    container_name: payflow-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: payflow-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  authservice:
    build:
      context: .
      dockerfile: services/PayFlow.AuthService/Dockerfile
    image: payflow-auth
    container_name: payflow-auth
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7093:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=PayFlowAuthDb;Username=postgres;Password=postgres
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__Exchange: payflow.exchange

  paymentservice:
    build:
      context: .
      dockerfile: services/PayFlow.PaymentService/Dockerfile
    image: payflow-payment
    container_name: payflow-payment
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7009:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=PayFlowPaymentDb;Username=postgres;Password=postgres
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__Exchange: payflow.exchange

  walletservice:
    build:
      context: .
      dockerfile: services/PayFlow.WalletService/Dockerfile
    image: payflow-wallet
    container_name: payflow-wallet
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7224:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=PayFlowWalletDb;Username=postgres;Password=postgres
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__Exchange: payflow.exchange

  fraudservice:
    build:
      context: .
      dockerfile: services/PayFlow.FraudService/Dockerfile
    image: payflow-fraud
    container_name: payflow-fraud
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7169:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=PayFlowFraudDb;Username=postgres;Password=postgres
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__Exchange: payflow.exchange

  notificationservice:
    build:
      context: .
      dockerfile: services/PayFlow.NotificationService/Dockerfile
    image: payflow-notification
    container_name: payflow-notification
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "7295:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=PayFlowNotificationDb;Username=postgres;Password=postgres
      RabbitMQ__HostName: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__UserName: guest
      RabbitMQ__Password: guest
      RabbitMQ__Exchange: payflow.exchange

volumes:
  postgres_data: